apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: evaluation-service
type: Opaque
stringData:
  SERVICE_API_KEY: "tm_key_64be2c4cfc31dd48f2c120da172686a42ae66189fba6d111a3b74e2abd3163ea"
